monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - domain
        - controller
        - store
        - user_factory

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

            applog:
                type: stream
                level: error
                path: "%kernel.logs_dir%/app.log"

            domain_log:
                type: stream
                level: error
                path: "%kernel.logs_dir%/Domain/errors.log"
                channels: ["domain"]

            domain_warning_log:
                type: stream
                level: warning
                path: "%kernel.logs_dir%/Domain/warnings.log"
                channels: ["domain"]

            domain_info_log:
                type: stream
                level: info
                path: "%kernel.logs_dir%/Domain/info.log"
                channels: ["domain"]

            controller_log:
                type: stream
                level: error
                path: "%kernel.logs_dir%/Controller/errors.log"
                channels: ["controller"]

            controller_warning_log:
                type: stream
                level: warning
                path: "%kernel.logs_dir%/Controller/warnings.log"
                channels: ["controller"]

            controller_info_log:
                type: stream
                level: info
                path: "%kernel.logs_dir%/Controller/info.log"
                channels: ["controller"]

            user_log:
              type: stream
              level: debug
              path: "$kernel.logs_dir%/Store/dev.log"
              channels: ["store", "user_factory"]

                


when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
