<?php

namespace App\Domain\User\Store\DTO\Collection;

use App\common\Abstract\AbstractCollection;
use App\Domain\User\Store\DTO\UserDTO;

class UserDtoCollection extends AbstractCollection
{
    public function __construct(UserDTO ...$userDTO) {
        $this->collection = $userDTO;
    }

    protected function getClassName(): string
    {
        return UserDTO::class;
    }

    public function offsetSet(mixed $offset, mixed $value): void
    {
        parent::offsetSet($offset, $value); // TODO: Change the autogenerated stub
    }
}