FROM php:8.2-fpm

RUN apt update && \
    apt install -y libpq-dev && \
    apt install git -y && \
    docker-php-ext-install pdo pdo_pgsql pgsql && \
    curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash && \
    apt install symfony-cli


RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer;

WORKDIR /app